---
  - name: NGINX | Installing NGINX
    yum: name=nginx state=latest
    notify:
      - restart nginx

  - name: NGINX | enabling NGINX
    service: name=nginx enabled=yes

  - name: Set /var/www/html permissions
    file: path=/var/www/ state=directory mode=0755 owner={{web_user}} group={{web_user}}
