---
- name: Install php-fpm and deps
  yum: name={{ item }} state=present enablerepo="remi-php56"
  with_items:
    - php
    - php-fpm
    - php-enchant
    - php-IDNA_Convert
    - php-mbstring
    - php-mysql
    - php-PHPMailer
    - php-process
    - php-simplepie
    - php-xml
    - php-mcrypt

- name: Disable default pool
  command: mv /etc/php-fpm.d/www.conf /etc/php-fpm.d/www.disabled creates=/etc/php-fpm.d/www.disabled
  notify: restart php-fpm

- name: Verifying composer
  command: /usr/local/sbin/composer --version
  ignore_errors: true
  register: composer_version_check
- debug: var=composer_version_check

- name: Download Composer
  get_url: url=https://getcomposer.org/installer dest=/opt/composer.phar mode=0755
  when: composer_version_check|failed

- name: Set composer globally
  command: php composer.phar --install-dir=/usr/local/sbin --filename=composer
  args:
    chdir: /opt/
  when: composer_version_check|failed

- name: set git token globally
  command: "/usr/local/sbin/composer config --global github-oauth.github.com {{git_deploy_access_token}}"
  when: composer_version_check|failed
