---
# Download and install REMI for Centos/RHEL version 7
- name: Download REMI Repo - Centos/RHEL 7
  get_url: url=http://rpms.remirepo.net/enterprise/remi-release-7.rpm dest=/tmp/remi-release-7.rpm
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"

- name: Install REMI Repo - Centos/RHEL 7
  command: rpm -ivh /tmp/remi-release-7.rpm creates=/etc/yum.repos.d/remi.repo
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"
