---
  - name: Create the repository for Mongodb-org
    copy: 
      src: "mongodb-org-{{ ansible_distribution }}.repo.j2" 
      dest: /etc/yum.repos.d/mongodb-org.repo

  - name: Update the repo
    command: yum clean expire-cache

  - name: Install the mongodb package
    yum: name={{ item }} state=present
    with_items:
     - libselinux-python
     - python-pip

  - name: Install the mongodb package
    yum: name={{ item }} enablerepo="mongodb-org-3.2" state=installed
    with_items:
     - mongodb-org
     - mongodb-org-server
     - mongodb-org-shell
     - mongodb-org-mongos
     - mongodb-org-tools
     - bc
    notify:
      - restart mongod

  - name: Install the latest pymongo package
    pip: name=pymongo state=latest use_mirrors=no
    ignore_errors: yes

  - name: mongod | enabling mongod
    service: name=mongod enabled=yes
    
  - name: start mongod
    service: name=mongod state=started
