---
  - name: verifying package.json
    stat: path=/var/www/html/package.json
    register: ghost_package

  - name: Copy the code from repository
    git: repo="https://github.com/TryGhost/Ghost.git" dest=/var/www/html/ clone=yes
    when: ghost_package.stat.exists == False


  - name: Install additional npm packages.
    npm:
      state: present
      path: /var/www/html

  - name: Install grunt local
    npm:
      name: grunt
      state: present
      path: /var/www/html

  - name: Initialize enviornment
    command: grunt init --force
    args:
      chdir: "/var/www/html/"

  - name: Initialize environment to prod
    command: grunt prod --force
    args:
      chdir: "/var/www/html/"
