---
  - name: install the 'Development tools' package group
    yum: name="@Development tools" state=present

  - name: install prereqs
    yum: name=git state=latest

  - name: selinux disable
    selinux: state=disabled

  - name: set hostname
    hostname: name={{ ansible_distribution }}.{{inventory_hostname}}

  - name: "Build hosts file"
    lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_default_ipv4.address }} {{item}}" state=present
    when: hostvars[item].ansible_default_ipv4.address is defined
    with_items: play_hosts
